server:
  port: 8088

spring:
  datasource:
    # 集群时一定要写内网IP
    url: jdbc:mysql://localhost:3306/foodie_shop_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    password: root
  redis:
    database: 1
    host: 192.168.1.112
    port: 6379
    password: root

mybatis:
  # 生产不需要打印SQL日志
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # SQL日志打印