############################################################
#
# web访问端口号  约定：8088
#
############################################################
server:
#  port: 8088 # 挂件补充端口号
  tomcat:
    uri-encoding: UTF-8
  max-http-header-size: 80KB

# 测试SpringBoot Actuator
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: '*'
# SpringBoot Actuator Info
info:
  project-name: foodie-dev
  author: jsonyao
  owner-email: yaocs2@qq.com

############################################################
#
# 配置数据源信息
#
############################################################
spring:
  # SpringBoot Admin
  boot:
    admin:
      client:
        url: http://localhost:8988
        instance:
          name: foodie-dev
  profiles:
    # 除了配置文件, 还可以通过profiles指定配置文件实现
    active: dev
  datasource:                                           # 数据源的相关配置
    type: com.zaxxer.hikari.HikariDataSource          # 数据源类型：HikariCP
    driver-class-name: com.mysql.jdbc.Driver          # mysql驱动
#    url: jdbc:mysql://localhost:3306/foodie_shop_dev?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    username: root
#    password: root
    hikari:
      connection-timeout: 30000       # 等待连接池分配连接的最大时长（毫秒），超过这个时长还没可用的连接则发生SQLException， 默认:30秒
      minimum-idle: 5                 # 最小连接数
      maximum-pool-size: 20           # 最大连接数
      auto-commit: true               # 自动提交
      idle-timeout: 600000            # 连接超时的最大时长（毫秒），超时则被释放（retired），默认:10分钟
      pool-name: DateSourceHikariCP     # 连接池名字
      max-lifetime: 1800000           # 连接的生命时长（毫秒），超时而且没被使用则被释放（retired），默认:30分钟 1800000ms
      connection-test-query: SELECT 1
  servlet:
    multipart:
      max-file-size: 512000           # 文件上传大小限制为500kb: 500 * 1024
      max-request-size: 512000        # 文件上传请求大小限制为500kb: 500 * 1024
#  session:
#    store-type: redis

############################################################
#
# mybatis 配置
#
############################################################
mybatis:
  type-aliases-package: com.imooc.pojo          # 所有POJO类所在包路径
  mapper-locations: classpath:mapper/*.xml      # mapper映射文件
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl    # SQL日志打印

############################################################
#
# mybatis mapper 配置
#
############################################################
# 通用 Mapper 配置
mapper:
  # myMapper接口
  mappers: com.imooc.my.mapper.MyMapper
  # 是否自动补全username != ''
  not-empty: false
  # 数据库方言MySQL
  identity: MYSQL
# 分页插件配置
pagehelper:
  # 数据库方言MySQL
  helperDialect: mysql
  # 是否支持分页参数传递
  supportMethodsArguments: true

# 整合Javamelody监控
javamelody:
  # 是否整合Javamelody, 默认为true
  enabled: true
  # 排除不想监控的数据源
  excluded-datasources: secretSource,topSecretSource,jsonYaoDataSource
  # 是否启用Spring Service & controller的监控, 默认是true
  spring-monitoring-enabled: true
  # 初始化配置项
  init-parameters:
    # 是否记录http请求
    log: true
    # 哪些路径不用被监控, 默认静态文件不用被监控
    #url-exclude-pattern: (/webjars/.*|/css/.*|/images/.*|/fonts/.*|/js/.*)
    # 用来转换http请求的路径, 将其中动态的部分删除
    #http-transform-pattern: \d+
    # 设置账号密码
    authorized-users: admin:pwd
    # 监控数据存储路径
    #storage-directory: /tmp/javamelody
    # Javamelody访问路径, 默认是/monitoring
    #monitoring-path: /admin/performance
  # 整合SpringBoot Actuator => http://localhost:8088/actuator/monitoring & 账号密码失效
  management-endpoint-monitoring-enabled: true